/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8/samples
 */

plugins {
    java
    checkstyle
    jacoco
    id("org.sonarqube") version "3.4.0.2513"
}

object Versions {
    const val JUNIT = "5.8.2"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-engine:${Versions.JUNIT}")
    testImplementation("org.junit.jupiter:junit-jupiter-api:${Versions.JUNIT}")
    testImplementation("org.junit.jupiter:junit-jupiter-params:${Versions.JUNIT}")
}

tasks.jacocoTestReport {
    reports {
        xml.required.set(true)
        xml.outputLocation
            .set(File("$buildDir/reports/jacoco/test/jacoco.xml"))
    }
}

tasks.test {
    useJUnitPlatform()
}
